; file uploads & forms
upload_max_filesize = 15M
post_max_size = 20M
max_input_vars = 4096

; sessions: README suggests 24h (must be global)
session.gc_maxlifetime = 86400

; helpful in dev
display_errors = On
error_reporting = E_ALL
